import{a as d,S as y,i as l}from"./assets/vendor-Dty-8Emr.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h="52827134-53a8d98a66d236597fa2c26fa",b=40,L=d.create({baseURL:"https://pixabay.com/api/",params:{key:h,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:b}});function P(o){return typeof o!="string"?Promise.reject(new Error("Query must be a string")):L.get("",{params:{q:o}}).then(t=>t.data)}const c=document.querySelector(".gallery"),u=document.querySelector(".loader"),w=new y(".gallery a",{captionsData:"alt",captionDelay:250});function A(o){if(!c||!Array.isArray(o)||o.length===0)return;const t=o.map(i=>{const{webformatURL:a,largeImageURL:e,tags:r,likes:n,views:m,comments:p,downloads:g}=i;return`
        <li class="gallery__item">
          <a class="gallery__link" href="${e}">
            <img class="gallery__image" src="${a}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><br>${n}</p>
            <p class="info-item"><b>Views</b><br>${m}</p>
            <p class="info-item"><b>Comments</b><br>${p}</p>
            <p class="info-item"><b>Downloads</b><br>${g}</p>
          </div>
        </li>
      `}).join("");c.insertAdjacentHTML("beforeend",t),w.refresh()}function _(){c&&(c.innerHTML="")}function q(){u&&u.classList.add("is-loading")}function S(){u&&u.classList.remove("is-loading")}const s=document.querySelector(".form"),f=s?s.querySelector('input[name="search-text"]'):null,v=document.querySelector(".gallery");(!s||!f||!v)&&console.error('Required DOM elements not found: .form, input[name="search-text"], .gallery');s&&s.addEventListener("submit",R);function R(o){o.preventDefault();const t=f.value.trim();if(!t){l.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}_(),q(),P(t).then(i=>{if(!i||!Array.isArray(i.hits)||i.hits.length===0){l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}A(i.hits),l.success({title:"Found",message:`Found ${i.totalHits} images.`,position:"topRight",timeout:2e3})}).catch(()=>{l.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}).finally(()=>{S()})}
//# sourceMappingURL=index.js.map
